### ISSUE TITLE
程序的正确性以及其它问题

### ISSUE THREAD

**Issue by yhw605** [luohongk/PseudorangeSPP#1]
# 算法的正确性问题
不同历元下计算的XYZ值相差极大，而且和data文件夹下ABPO测站的RINEX文件中记录的概略坐标差距也非常大，请问是哪里出现了问题。
程序是git clone下来之后就直接运行的，没有做过改动。
部分运行结果如下：
```
平差后的X坐标: 75388.08220433863 平差后的Y坐标: -384998.35008568317 平差后的Z坐标: -944876.1617440679
平差后的X坐标: 41833.51997880312 平差后的Y坐标: -350492.19593357295 平差后的Z坐标: -940969.1625764058
平差后的X坐标: 8290.520810123999 平差后的Y坐标: -316007.3245349601 平差后的Z坐标: -937058.5214207494
平差后的X坐标: -25239.796604442876 平差后的Y坐标: -281543.9021608457 平差后的Z坐标: -933143.5599149042
平差后的X坐标: -58759.06675519375 平差后的Y坐标: -247101.63901292533 平差后的Z坐标: -929224.5692757354
平差后的X坐标: -92263.46999682812 平差后的Y坐标: -212683.70272580534 平差后的Z坐标: -925300.9292708137
平差后的X坐标: -125754.59188686637 平差后的Y坐标: -178289.57949546725 平差后的Z坐标: -921372.9773503826
平差后的X坐标: -159229.00409514038 平差后的Y坐标: -143921.6780750081 平差后的Z坐标: -917439.7771018879
平差后的X坐标: -192687.3739457908 平差后的Y坐标: -109581.546318762 平差后的Z坐标: -913502.6865292513
平差后的X坐标: -226130.40312867193 平差后的Y坐标: -75265.93226591498 平差后的Z坐标: -909559.961658279
平差后的X坐标: -259556.0324708554 平差后的Y坐标: -40978.981911085546 平差后的Z坐标: -905612.3650424727
平差后的X坐标: -292962.9659506562 平差后的Y坐标: -6721.6742126867175 平差后的Z坐标: -901659.547249137
```
而RINEX中记载的概略坐标为
```
  4097216.5539  4429119.1897 -2065771.1988                  APPROX POSITION XYZ
```

# 电离层、对流层改正
在程序中似乎没有看到相关的代码，未来是否会支持这些功能。

# RINEX格式支持
是否会支持RINEX V3和RINEX V4格式的观测文件和导航文件：毕竟现在下载的数据很多已经是RINEX V3格式了，同时，RINEX V4格式导航文件中已经支持诸如BDGIM广播参数（以此为例只是因为个人刚好只了解这个）等其它新一代的导航电文。

**Comment by luohongk** [comment]
是的，代码还有bug，没时间维护了，此代码只是提供一个大体思路参考，建议还是去看看rtklib，代码不涉及电离层，对流层改正，但是也可以自己在误差项中加这个。（希望你能帮我看看代码的bug在那儿🤣）



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Hanwen Yan ***@***.***&gt;
发送时间: 2024年8月24日 18:49
收件人: luohongk/PseudorangeSPP ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [luohongk/PseudorangeSPP] 程序的正确性以及其它问题 (Issue #1)





 
算法的正确性问题
 
不同历元下计算的XYZ值相差极大，而且和data文件夹下ABPO测站的RINEX文件中记录的概略坐标差距也非常大，请问是哪里出现了问题。
 程序是git clone下来之后就直接运行的，没有做过改动。
 部分运行结果如下：
 平差后的X坐标: 75388.08220433863 平差后的Y坐标: -384998.35008568317 平差后的Z坐标: -944876.1617440679 平差后的X坐标: 41833.51997880312 平差后的Y坐标: -350492.19593357295 平差后的Z坐标: -940969.1625764058 平差后的X坐标: 8290.520810123999 平差后的Y坐标: -316007.3245349601 平差后的Z坐标: -937058.5214207494 平差后的X坐标: -25239.796604442876 平差后的Y坐标: -281543.9021608457 平差后的Z坐标: -933143.5599149042 平差后的X坐标: -58759.06675519375 平差后的Y坐标: -247101.63901292533 平差后的Z坐标: -929224.5692757354 平差后的X坐标: -92263.46999682812 平差后的Y坐标: -212683.70272580534 平差后的Z坐标: -925300.9292708137 平差后的X坐标: -125754.59188686637 平差后的Y坐标: -178289.57949546725 平差后的Z坐标: -921372.9773503826 平差后的X坐标: -159229.00409514038 平差后的Y坐标: -143921.6780750081 平差后的Z坐标: -917439.7771018879 平差后的X坐标: -192687.3739457908 平差后的Y坐标: -109581.546318762 平差后的Z坐标: -913502.6865292513 平差后的X坐标: -226130.40312867193 平差后的Y坐标: -75265.93226591498 平差后的Z坐标: -909559.961658279 平差后的X坐标: -259556.0324708554 平差后的Y坐标: -40978.981911085546 平差后的Z坐标: -905612.3650424727 平差后的X坐标: -292962.9659506562 平差后的Y坐标: -6721.6742126867175 平差后的Z坐标: -901659.547249137  
而RINEX中记载的概略坐标为
   4097216.5539  4429119.1897 -2065771.1988                  APPROX POSITION XYZ  
电离层、对流层改正
 
在程序中似乎没有看到相关的代码，未来是否会支持这些功能。
 
RINEX格式支持
 
是否会支持RINEX V3和RINEX V4格式的观测文件和导航文件：毕竟现在下载的数据很多已经是RINEX V3格式了，同时，RINEX V4格式导航文件中已经支持诸如BDGIM广播参数（以此为例只是因为个人刚好只了解这个）等其它新一代的导航电文。

**Comment by luohongk** [comment]
另外，不会支持其他格式，本身这个小仓库也就是我写着玩玩儿的，抛砖引玉吧，哈哈哈



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Hanwen Yan ***@***.***&gt;
发送时间: 2024年8月24日 18:49
收件人: luohongk/PseudorangeSPP ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [luohongk/PseudorangeSPP] 程序的正确性以及其它问题 (Issue #1)





 
算法的正确性问题
 
不同历元下计算的XYZ值相差极大，而且和data文件夹下ABPO测站的RINEX文件中记录的概略坐标差距也非常大，请问是哪里出现了问题。
 程序是git clone下来之后就直接运行的，没有做过改动。
 部分运行结果如下：
 平差后的X坐标: 75388.08220433863 平差后的Y坐标: -384998.35008568317 平差后的Z坐标: -944876.1617440679 平差后的X坐标: 41833.51997880312 平差后的Y坐标: -350492.19593357295 平差后的Z坐标: -940969.1625764058 平差后的X坐标: 8290.520810123999 平差后的Y坐标: -316007.3245349601 平差后的Z坐标: -937058.5214207494 平差后的X坐标: -25239.796604442876 平差后的Y坐标: -281543.9021608457 平差后的Z坐标: -933143.5599149042 平差后的X坐标: -58759.06675519375 平差后的Y坐标: -247101.63901292533 平差后的Z坐标: -929224.5692757354 平差后的X坐标: -92263.46999682812 平差后的Y坐标: -212683.70272580534 平差后的Z坐标: -925300.9292708137 平差后的X坐标: -125754.59188686637 平差后的Y坐标: -178289.57949546725 平差后的Z坐标: -921372.9773503826 平差后的X坐标: -159229.00409514038 平差后的Y坐标: -143921.6780750081 平差后的Z坐标: -917439.7771018879 平差后的X坐标: -192687.3739457908 平差后的Y坐标: -109581.546318762 平差后的Z坐标: -913502.6865292513 平差后的X坐标: -226130.40312867193 平差后的Y坐标: -75265.93226591498 平差后的Z坐标: -909559.961658279 平差后的X坐标: -259556.0324708554 平差后的Y坐标: -40978.981911085546 平差后的Z坐标: -905612.3650424727 平差后的X坐标: -292962.9659506562 平差后的Y坐标: -6721.6742126867175 平差后的Z坐标: -901659.547249137  
而RINEX中记载的概略坐标为
   4097216.5539  4429119.1897 -2065771.1988                  APPROX POSITION XYZ  
电离层、对流层改正
 
在程序中似乎没有看到相关的代码，未来是否会支持这些功能。
 
RINEX格式支持
 
是否会支持RINEX V3和RINEX V4格式的观测文件和导航文件：毕竟现在下载的数据很多已经是RINEX V3格式了，同时，RINEX V4格式导航文件中已经支持诸如BDGIM广播参数（以此为例只是因为个人刚好只了解这个）等其它新一代的导航电文。
